aes:
  iv: unforethoughtful
  key: perineorrhaphies

---
spring:
  profiles: dev
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nztrip?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false
  devtools:
    restart:
      exclude: static/**, templates/**
debug: true

---
spring:
  profiles: production

---
spring:
  profiles: test
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aotearoa.cktnjjqgvdei.ap-northeast-1.rds.amazonaws.com:3306/aotearoa?useUnicode=true&characterEncoding=UTF-8
    username: aotearoa
    password: Fitibo~1
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false

---
email:
    host: smtp.126.com
    port: 25
    username: zi___yue@126.com
    password: Ilove126
    javaMailProperties:
      mail.smtp.auth: true

---
template:
    email: |
      <html><body><div>
      <p>#VENDORNAME#,</p>
      <br/>
      <p>Please kindly help us to make the reservation as blew:</p>
      <br/>
      <p>TOUR: #TOUR#</p>
      <p>NAME: #NAME#</p>
      #TOURINFO#
      <br/>
      <p>A prompt replay would greatly oblige us.</p>
      <br/>
      <p>Many thanks for your support.</p>
      <br/>
      <p>Best Regards</p>
      <br/>
      <p>Reservation Team</p>
      <p style="color: dodgerblue">the <span style="font-weight: bold">Easy Efficient Excellent</span> travel with <span style="font-weight: bold">EYOUNZ Limited</span></p>
      <p>Tel & Fax: +64 (0)3 357 4405</p>
      <p>Address: 30 Durey Rd, Christchurch Airport Internatinal Terminal Building, Christchurch 8053</p>
      </div></body></html>