aes:
  iv: unforethoughtful
  key: perineorrhaphies

---
spring:
  profiles: dev
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nztrip?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false
  devtools:
    restart:
      exclude: static/**, templates/**
debug: true

---
spring:
  profiles: production

---
spring:
  profiles: test
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aotearoa.cktnjjqgvdei.ap-northeast-1.rds.amazonaws.com:3306/aotearoa?useUnicode=true&characterEncoding=UTF-8
    username: aotearoa
    password: Fitibo~1
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false

---
email:
    host: smtp.126.com
    port: 25
    username: zi___yue@126.com(your email)
    password: ****
    javaMailProperties:
      mail.smtp.auth: true

---
template:
    reservationemail:
      from: zi___yue@126.com(your email)
      subject: Make Reservation
      content: |
        <html><body><div>
        #VENDORNAME#,<br><br>
        Please kindly help us to make the reservation as blew:<br><br>
        TOUR: #TOUR#<br>
        NAME: #NAME#<br>
        #TOURINFO#<br>
        A prompt replay would greatly oblige us.<br><br>
        Many thanks for your support.<br><br>
        Best Regards<br><br>
        Reservation Team<br>
        <span style="color: dodgerblue">the <span style="font-weight: bold">Easy Efficient Excellent</span> travel with <span style="font-weight: bold">EYOUNZ Limited</span></span><br>
        Tel & Fax: +64 (0)3 357 4405<br>
        Address: 30 Durey Rd, Christchurch Airport Internatinal Terminal Building, Christchurch 8053
        </div></body></html>